VERSION 6
BEGIN SCHEMATIC
    BEGIN ATTR DeviceFamilyName "xa9500xl"
        DELETE all:0
        EDITNAME all:0
        EDITTRAIT all:0
    END ATTR
    BEGIN NETLIST
        SIGNAL XLXN_23
        SIGNAL XLXN_24
    END NETLIST
    BEGIN SHEET 1 7040 5440
    END SHEET
END SCHEMATIC
